// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered shoe care recommendation tool.
 *
 * - shoeAdvisor - A function that handles the shoe care recommendation process.
 * - ShoeAdvisorInput - The input type for the shoeAdvisor function.
 * - ShoeAdvisorOutput - The return type for the shoeAdvisor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ShoeAdvisorInputSchema = z.object({
  shoeType: z
    .string()
    .describe('The type of shoe (e.g., sneakers, boots, leather shoes).'),
  material: z
    .string()
    .describe('The material of the shoe (e.g., canvas, leather, suede).'),
  problem: z
    .string()
    .describe('A description of the problem with the shoe (e.g., dirty, scuffed, yellowing).'),
});
export type ShoeAdvisorInput = z.infer<typeof ShoeAdvisorInputSchema>;

const ShoeAdvisorOutputSchema = z.object({
  recommendation: z
    .string()
    .describe('The recommended cleaning service for the shoe.'),
  reasoning: z
    .string()
    .describe('The reasoning behind the recommendation.'),
});
export type ShoeAdvisorOutput = z.infer<typeof ShoeAdvisorOutputSchema>;

export async function shoeAdvisor(input: ShoeAdvisorInput): Promise<ShoeAdvisorOutput> {
  return shoeAdvisorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'shoeAdvisorPrompt',
  input: {schema: ShoeAdvisorInputSchema},
  output: {schema: ShoeAdvisorOutputSchema},
  prompt: `Anda adalah seorang ahli penasihat perawatan sepatu untuk layanan bernama elsclean.id. Tugas Anda adalah menganalisis masukan pengguna dan merekomendasikan layanan yang paling sesuai dari daftar yang disediakan.

Analisis jenis sepatu, bahan, dan terutama deskripsi masalah pengguna untuk membuat rekomendasi Anda.

**Input Pengguna:**
- Jenis Sepatu: {{{shoeType}}}
- Bahan: {{{material}}}
- Masalah: {{{problem}}}

**Layanan Kami:**
- **Deep Cleaning**: Terbaik untuk kotoran berat, noda yang meresap, dan pembersihan menyeluruh di bagian dalam dan luar. Pilih ini untuk sepatu yang sangat kotor.
- **Fast Cleaning**: Pembersihan cepat di permukaan luar sepatu. Ideal untuk kotoran ringan, debu, dan penyegaran cepat.
- **Unyellowing**: Khusus untuk merawat dan mengembalikan sol yang menguning pada sneakers, mengembalikan warna putih aslinya.
- **Repaint**: Digunakan untuk mengembalikan atau mengubah total warna sepatu. Pilih ini jika pengguna menyebutkan warna pudar, lecet yang menghilangkan warna, atau menginginkan tampilan baru.

**Tugas Anda:**
1.  **Rekomendasikan satu layanan** dari daftar di atas yang secara langsung mengatasi masalah pengguna.
2.  **Berikan alasan yang jelas** untuk rekomendasi Anda, jelaskan mengapa layanan spesifik tersebut adalah yang paling cocok berdasarkan masalah yang dijelaskan.
3.  **Gunakan Bahasa Indonesia** untuk semua output (rekomendasi dan alasan).`,
});

const shoeAdvisorFlow = ai.defineFlow(
  {
    name: 'shoeAdvisorFlow',
    inputSchema: ShoeAdvisorInputSchema,
    outputSchema: ShoeAdvisorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
