// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered shoe care recommendation tool.
 *
 * - shoeAdvisor - A function that handles the shoe care recommendation process.
 * - ShoeAdvisorInput - The input type for the shoeAdvisor function.
 * - ShoeAdvisorOutput - The return type for the shoeAdvisor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ShoeAdvisorInputSchema = z.object({
  shoeType: z
    .string()
    .describe('The type of shoe (e.g., sneakers, boots, leather shoes).'),
  material: z
    .string()
    .describe('The material of the shoe (e.g., canvas, leather, suede).'),
  problem: z
    .string()
    .describe('A description of the problem with the shoe (e.g., dirty, scuffed, yellowing).'),
});
export type ShoeAdvisorInput = z.infer<typeof ShoeAdvisorInputSchema>;

const ShoeAdvisorOutputSchema = z.object({
  recommendation: z
    .string()
    .describe('The recommended cleaning service for the shoe.'),
  reasoning: z
    .string()
    .describe('The reasoning behind the recommendation.'),
});
export type ShoeAdvisorOutput = z.infer<typeof ShoeAdvisorOutputSchema>;

export async function shoeAdvisor(input: ShoeAdvisorInput): Promise<ShoeAdvisorOutput> {
  return shoeAdvisorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'shoeAdvisorPrompt',
  input: {schema: ShoeAdvisorInputSchema},
  output: {schema: ShoeAdvisorOutputSchema},
  prompt: `You are an expert shoe care advisor for a service called elsclean.id. Your task is to analyze the user's input and recommend the most suitable service from the list provided.

Analyze the user's shoe type, material, and especially the problem description to make your recommendation.

**User Input:**
- Shoe Type: {{{shoeType}}}
- Material: {{{material}}}
- Problem: {{{problem}}}

**Our Services:**
- **Deep Cleaning**: Best for heavy dirt, deep-set stains, and overall thorough cleaning inside and out. Choose this for very dirty shoes.
- **Fast Cleaning**: A quick surface-level cleaning for the outside of the shoe. Ideal for light dirt, dust, and a quick refresh.
- **Unyellowing**: Specifically for treating and restoring yellowed soles on sneakers, bringing back the original white color.
- **Repaint**: Used to restore or completely change the color of a shoe. Choose this if the user mentions faded color, scuffs that have removed color, or wanting a new look.

**Your Task:**
1.  **Recommend one service** from the list above that directly addresses the user's problem.
2.  **Provide a clear reasoning** for your recommendation, explaining why that specific service is the best fit based on the described problem.`,
});

const shoeAdvisorFlow = ai.defineFlow(
  {
    name: 'shoeAdvisorFlow',
    inputSchema: ShoeAdvisorInputSchema,
    outputSchema: ShoeAdvisorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
