// This is an autogenerated file from Firebase Studio.
// Add your Firebase configuration object here.
// You can find this in the Firebase console for your project.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore, collection, type DocumentData} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDa0mHjrTK1O73yosGLrE7I5Q51eoNa3sg",
  authDomain: "stationery-inventory.firebaseapp.com",
  projectId: "stationery-inventory",
  storageBucket: "stationery-inventory.firebasestorage.app",
  messagingSenderId: "812550241868",
  appId: "1:812550241868:web:ebf1e04bbfa98a7d56fee9"
};

// Initialize Firebase
let app;
try {
    app = getApp();
} catch (e) {
    if (!getApps().length) {
        app = initializeApp(firebaseConfig);
    } else {
        app = getApp();
    }
}

const db = getFirestore(app);


// Data type for ads
export interface AdData extends DocumentData {
  id: string;
  image: string;
  imageHint: string;
  title: string;
  description: string;
  link: string;
}

export {db};
