// This is an autogenerated file from Firebase Studio.
// Add your Firebase configuration object here.
// You can find this in the Firebase console for your project.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore, collection, type DocumentData} from 'firebase/firestore';

// TODO: Paste your Firebase config object here.
const firebaseConfig = {
  apiKey: 'PASTE_YOUR_API_KEY_HERE',
  authDomain: 'PASTE_YOUR_AUTH_DOMAIN_HERE',
  projectId: 'PASTE_YOUR_PROJECT_ID_HERE',
  storageBucket: 'PASTE_YOUR_STORAGE_BUCKET_HERE',
  messagingSenderId: 'PASTE_YOUR_MESSAGING_SENDER_ID_HERE',
  appId: 'PASTE_YOUR_APP_ID_HERE',
};

// Initialize Firebase
let app;
try {
    app = getApp();
} catch (e) {
    if (!getApps().length) {
        app = initializeApp(firebaseConfig);
    } else {
        app = getApp();
    }
}

const db = getFirestore(app);


// Data type for ads
export interface AdData extends DocumentData {
  id: string;
  image: string;
  imageHint: string;
  title: string;
  description: string;
  link: string;
}

export {db};
